name: build-suricata

on:
  push:
    tags:
      - 'v*'        # e.g. v7.0.11

permissions:
  contents: write   # needed to publish a Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
            triplet: linux-amd64
          - os: ubuntu-24.04-arm
            arch: arm64
            triplet: linux-arm64
          - os: macos-13
            arch: amd64
            triplet: macos-amd64
          - os: macos-14
            arch: arm64
            triplet: macos-arm64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install build deps (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          # Official minimal deps + tools per docs
          sudo apt-get install -y autoconf automake build-essential cargo cbindgen \
            libjansson-dev libpcap-dev libpcre2-dev libtool libyaml-dev make pkg-config rustc zlib1g-dev
          # Optional (x86_64 only) for faster pattern matching:
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            sudo apt-get install -y libhyperscan-dev || true
          fi

      - name: Install build deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          # Brew provides the needed libs/tools; libpcap is available via macOS/brew
          brew install autoconf automake libtool pkg-config jansson libmagic libyaml pcre2 libpcap lz4 rust cbindgen

      - name: Configure & build
        run: |
          ./configure \
            --disable-gccmarch-native \
            --prefix=/opt/suricata \
            --sysconfdir=/etc \
            --localstatedir=/var
          make -j"$(sysctl -n hw.logicalcpu 2>/dev/null || nproc)"

      - name: Stage install & package tarball
        run: |
          DEST="$PWD/stage"
          make DESTDIR="$DEST" install
          cd "$DEST"
          tar czf "$GITHUB_WORKSPACE/suricata-${VER}-${{ matrix.triplet }}.tar.gz" .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: suricata-${{ env.VER }}-${{ matrix.triplet }}
          path: suricata-${{ env.VER }}-${{ matrix.triplet }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
      - name: Publish GitHub Release with binaries
        uses: softprops/action-gh-release@v2
        with:
          files: "**/*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
